### ISSUE TITLE
Doesn't copy single-character tags liike v, w, etc...

### ISSUE THREAD

**Issue by GlassedSilver** [JetBoom/boorutagparser#20]
Pretty common on danbooru and very much a problem not to grab them, since they aren't supplementary tags, but main tags for gestures.

**Comment by JetBoom** [comment]
https://github.com/JetBoom/boorutagparser/commit/3336fcc63cc7b95f3efeecb723aa331eb9ccc99f

**Comment by GlassedSilver** [comment]
God speed and many thanks for this quick update.

One thing though if you don't mind me pointing this out:
you forgot to update the version tag, that way Tampermonkey would update the script automatically. :)
