### ISSUE TITLE
Boorutagparser will not download higher quality png on yande.re

### ISSUE THREAD

**Issue by ulilpieceofs** [JetBoom/boorutagparser#7]
The problem:
When using "download with tags" option with boorutagparser-server, the server will download jpg instead of higher quality png. 

sites tested:
yande.re

How to reproduce:
1. go to yande.re
2. find an image with both jpg and png versions (e.g. https://yande.re/post/show/473170)
3. press \ to download with tags
4. the jpg version is downloaded

**Comment by UnlimitedArk** [comment]
Can confirm, although if possible i'd actually prefer being given the option since with yande.re specifically i find myself preferring the jpg version more often than not as it's an acceptable smaller version (except on tall images) unlike sankaku's and danbooru's samples

**Comment by ulilpieceofs** [comment]
Agreed. Having it as an option would be the best.
