### ISSUE TITLE
Getting a authentication popup with script enabled

### ISSUE THREAD

**Issue by Cupbox** [JetBoom/boorutagparser#9]
Hey. 
For the last week I get the following each time I browse to a new page on rule34.xxx with your script enabled.
![image](https://user-images.githubusercontent.com/13769570/58743505-561ce700-8422-11e9-93d5-f087946d3b53.png)

**Comment by UnlimitedArk** [comment]
Same on Sankaku, i had to turn it off since it popped up on every page.

**Comment by JetBoom** [comment]
https://github.com/JetBoom/boorutagparser/commit/e76cdbaa012cdadf655c8d66821d7d11042edefb
